plugins:
- jekyll-relative-links
- jekyll-loading-lazy

relative_links:
  enabled: true
  collections: true

theme: minima

include:
  - README.md
  - film_packaging/by_brand.md
  - LICENSE

title: Film Packaging Archive
description: High-resolution scans of photographic film packaging

url: https://dekunukem.github.io
baseurl: /jekyll_test